spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false #关闭缓存
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/static/
  messages:
    basename: i18m/messages

comment.avatar: /img/avatar.png

